### ISSUE TITLE
How count token from prompt?

### ISSUE THREAD

**Issue by samatzp** [orenagiv/langchain_tiktoken#1]

**Comment by davidmigloz** [comment]
```
final tiktoken = getEncoding('cl100k_base');
final count = tiktoken.encode('your prompt').length;
```

If your prompt is a chat prompt you need to count some additional tokens. You can check how LangChain.dart does it here:
https://github.com/davidmigloz/langchain_dart/blob/cff2c58a19fb7503ec17744b4edaaa4008227aa3/packages/langchain_openai/lib/src/chat_models/chat_openai.dart#L334-L395
